name: Build and release crate package

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cargo test
        run: cargo test

      - name: sudo apt install tree
        run: sudo apt install tree

      - name: cargo package
        run: cargo package

      - name: cd target/package
        run: cd target/package

      - name: Delete crate file
        run: rm *.crate

      - name: Rename directory to output
        run: mv frank_jwt* ./output

      - name: tree
        run: tree

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: Release ${{ github.ref_name }}
          files: |
            ./target/package/output
